string = "AAAA,KACE,eAAA,CACA,eAAA,CACA,8DAAA,CACA,eAAA,CACA,cAGF,6BAME,cAAA,CACA,mBAAA,CACA,mBAAA,CACA,cAGF,KACE,YAAA,CACA,kBAEA,WACE,aAAA,CACA,WAAA,CACA,kBAEA,iBACE,oBAAA,CAEA,wBAAA,CACA,eAAA,CACA,sBAAA,CACA,YAAA,CACA,sBAGJ,YACE,YAAA,CACA,WAAA,CACA,gBAKJ,gBACE,eAAA,CACA,UAAA,CACA,oBAAA,CACA,4BAAA,CACA,iBAAA,CACA,eAAA,CACA,gBAAA,CACA,cAAA,CACA,gBAAA,CACA,iBAAA,CACA,eAEF,sBACE,kBAAA,CACA,WAEF,6CAEE,UAAA,CACA,UAAA,CACA,aAAA,CACA,iBAAA,CACA,OAAA,CACA,MAAA,CACA,UAAA,CACA,gBAEF,sBACE,UAAA,CACA,SAEF,cACE,cAAA,CACA,aAAA,CACA,KAAA,CACA,YAAA,CACA,WAAA,CACA,eAAA,CACA,YAAA,CACA,aAEF,gBACE,WAAA,CACA,iBAAA,CACA,QAAA,CACA,WAAA,CACA,uBAAA,CACA,+BAAA,CACA,2BAAA,CACA,4BAAA,CACA,0BAAA,CACA"

strings = string.split(',')

print(len(strings))
